function [analysisFiles, process_noise_manual, outputLoc] = PulseSetup(input, props)

    if strcmpi(input,'all_dbg')
        process_noise_manual = 1;
        loc = props('noise_input'); %'C:\Users\Dan\Desktop\bcvs\norm with d\';
        edf_list = dir(fullfile(loc, '**/*.edf'));
        xml_list = dir(fullfile(loc, '**/*edf.XML'));

        if (length(edf_list) ~= length(xml_list))
            error('unmatching edf''s and xmls')
        end

        analysisFiles = cell(length(edf_list), 4);

        for i = 1:length(edf_list)
            analysisFiles{i, 2} = fullfile(edf_list(i).folder, edf_list(i).name);
            analysisFiles{i, 3} = fullfile(xml_list(i).folder, xml_list(i).name);
            [~, name, ~] = fileparts(analysisFiles{i, 2});
            analysisFiles{i, 1} = name;
        end

        disp('Select output location');
        outputLoc = props('noise_output'); %'C:\Users\Dan\Desktop\Output\';

        search = dir(fullfile(outputLoc, '**/pulse_analysis_status.csv'));

        if isempty(search)
            createStatusFile(outputLoc, analysisFiles);
        end

        %% pulse status format =
        % file base name,  edf location, xml location, code for noise
        % marking status (0=unmarked,1=marked,other=error), code for
        % analysis (0=unmarked,1=marked,other=error),
        search = dir(fullfile(outputLoc, '**/pulse_analysis_status.csv'));
        search = fullfile(search(1).folder, search(1).name);

        % autogenerated from matlablab uiopen import
        delimiter = ',';
        startRow = 2;
        fileID = fopen(search, 'r');
        formatSpec = '%s%f%f%[^\n\r]';
        dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow - 1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        fclose(fileID);
        dataArray([2, 3]) = cellfun(@(x) num2cell(x), dataArray([2, 3]), 'UniformOutput', false);
        dataArray(1) = cellfun(@(x) mat2cell(x, ones(length(x), 1)), dataArray(1), 'UniformOutput', false);
        status = [dataArray{1:end - 1}];

%         if length(status) ~= length(analysisFiles)
%             error('status file and files found do not match lengths')
%         end

%         for i = 1:length(status)
%             analysisFiles{i, 4} = status{i, 2};
%             analysisFiles{i, 5} = status{i, 3};
%         end
        analysisFiles{i, 4} = 0;
        analysisFiles{i, 5} = 0;
    elseif strcmpi(input,'random_auto_dbg')
        process_noise_manual = 0;
        folder_location = props('noise_input');
        [file_name,  file_folder, full_path] = RandomFileFromFolder(folder_location, '.edf');
        analysisFiles{1, 1} = file_name(1:end-4);
        analysisFiles{1, 2} = full_path;
        analysisFiles{1, 3} = fullfile(file_folder, [file_name '.XML']);
        analysisFiles{1, 4} = 0;
        analysisFiles{1, 5} = 0;
        outputLoc = props('noise_output');
        createStatusFile(outputLoc, analysisFiles)
        
    elseif strcmpi(input,'random_manual_dbg')
        process_noise_manual = 1;
        [file_name,  file_folder, full_path] = RandomFileFromFolder(props('noise_input'), '.edf');
        analysisFiles{1, 1} = file_name(1:end-4);
        analysisFiles{1, 2} = full_path;
        analysisFiles{1, 3} = fullfile(file_folder, [file_name '.XML']);
        analysisFiles{1, 4} = 0;
        analysisFiles{1, 5} = 0;
        outputLoc = props('noise_output')
        createStatusFile(outputLoc, analysisFiles)
    elseif strcmpi(input,'normal')
        process_noise_manual = 1;
        disp('Pulse Analysis Tool');
        disp('*********************');
        disp('Select location of data to be analyzed (will recursivly search for .edfs and matching .xmls)');
        loc = uigetdir('Select location of data to be analyzed (will recursivly search for .edfs and matching .xmls)');
        %loc = '/hdd/data/mesa/EDF All';

        if loc == 0
            return
        end

        edf_list = dir(fullfile(loc, '**/*.edf'));
        xml_list = dir(fullfile(loc, '**/*.edf.XML'));

        if (length(edf_list) ~= length(xml_list))
            error('unmatching edf''s and xmls')
        end

        analysisFiles = cell(length(edf_list), 4);

        for i = 1:length(edf_list)
            analysisFiles{i, 2} = fullfile(edf_list(i).folder, edf_list(i).name);
            analysisFiles{i, 3} = fullfile(xml_list(i).folder, xml_list(i).name);
            [~, name, ~] = fileparts(analysisFiles{i, 2});
            analysisFiles{i, 1} = name;
        end

        disp('Select output location');
        outputLoc = uigetdir('Select output location');
        %outputLoc = '/home/deeplab/Desktop/test';

        if outputLoc == 0
            return
        end

%         search = dir(fullfile(outputLoc, '**/pulse_analysis_status.csv'));
% 
%         if isempty(search)
%             createStatusFile(outputLoc, analysisFiles);
%         end
% 
%         %% pulse status format =
%         % file base name,  edf location, xml location, code for noise
%         % marking status (0=unmarked,1=marked,other=error), code for
%         % analysis (0=unmarked,1=marked,other=error),
%         search = dir(fullfile(outputLoc, '**/pulse_analysis_status.csv'));
%         search = fullfile(search(1).folder, search(1).name);
% 
%         % autogenerated from matlablab uiopen import
%         delimiter = ',';
%         startRow = 2;
%         fileID = fopen(search, 'r');
%         formatSpec = '%s%f%f%[^\n\r]';
%         dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow - 1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%         fclose(fileID);
%         dataArray([2, 3]) = cellfun(@(x) num2cell(x), dataArray([2, 3]), 'UniformOutput', false);
%         dataArray(1) = cellfun(@(x) mat2cell(x, ones(length(x), 1)), dataArray(1), 'UniformOutput', false);
%         status = [dataArray{1:end - 1}];
% 
%         if length(status) ~= length(analysisFiles)
%             error('status file and files found do not match lengths')
%         end
% 
%         for i = 1:length(status)
%             analysisFiles{i, 4} = status{i, 2};
%             analysisFiles{i, 5} = status{i, 3};
%         end

    else
        path = props('noise_input');
        [~, name, ~] = fileparts(path);

        analysisFiles{1} = name;
        analysisFiles{2} = path;
        analysisFiles{3} = strcat(path,'.XML');
        analysisFiles{4} = 0;
        analysisFiles{5} = 0;
        outputLoc = props('noise_output');
        process_noise_manual = 1;
    end

end

function createStatusFile(loc, analysisFWiles)
    fid = fopen(fullfile(loc, 'pulse_analysis_status.csv'), 'wt');
    fprintf(fid, 'Record,NoiseStatus,AnalysisStatus\n');

    for i = 1:size(analysisFiles,1)
        fprintf(fid, '%s,0,0\n', analysisFiles{i, 1});
    end

    fclose(fid);
end
